### ISSUE TITLE
Does this parser library provide us ...

### ISSUE THREAD

**Issue by KiJeong-Lim** [gallais/parseque#5]
parsers which returns a value for a given string in run-time?
I mean, can I make the parser such that, with this library,
```coq
Definition parseSQL : string -> SQL := (* with this library *).
Example parseSQL_test01
  : parserSQL "select ... "%string = (* the result *).
Proof. reflexivity. Qed.
```
? As I think as, this library provides us type-level parser combinators,
and so we cannot make such a parser combinator.
In conclusion, I want
```coq
Example test1
  : parse "1+1" expr = MkSingleton (EAdd (EEmb (TEmb (FLit 1))) (TEmb (FLit 1))).
Proof. reflexivity. Qed.
```
and I think that you've made a parser validator, that is, a compile-time parser.

**Comment by gallais** [comment]
We do have examples, e.g.

https://github.com/gallais/parseque/blob/27ef96b6c1f7b04cdbbbea9845f9d4c985712787/src/Examples.v#L48-L55

**Comment by KiJeong-Lim** [comment]
But I don't want a kind of
```coq
Example test : check $str $parser := $result.
```
I want
```
Example test : check $str $parser = $result.
Proof. reflexivity. Qed.
```
They are not the same level, the first is compile-time, the latter is run-time.

**Comment by gallais** [comment]
You can modify `check` to return an `option A` rather than a `Type` and have the two branches
on lines 44 & 45 return respectively `Some hd` and `None`.

**Comment by KiJeong-Lim** [comment]
Super thanks!!! I want it!
