### ISSUE TITLE
packaging with opam

### ISSUE THREAD

**Issue by womeier** [gallais/parseque#7]
I'd like to use this project in an opam-based setup. I was hoping, it could also be included in the opam-coq-archive.

What do you think about that?

I'm currently using my fork, see https://github.com/gallais/parseque/pull/6

relevant for https://github.com/WasmCert/WasmCert-Coq/issues/9

**Comment by gallais** [comment]
I am happy for it to be shipped, I just do not have time to maintain & deal with distribution.
Would you be happy to do it if I gave you full access to the repo?

**Comment by womeier** [comment]
thanks for the reply!

I'm happy to do the packaging (I'll probably have time for that in the summer.)

**Comment by jeromesimeon** [comment]
I'd be happy to push an initial release to opam-coq-archive. All that's needed from the repo maintainer is a GitHub release (which will provide a version number and tarball). The rest is a pretty simple PR on the opam-coq-archive repo.

**Comment by womeier** [comment]
> I'd be happy to push an initial release to opam-coq-archive. All that's needed from the repo maintainer is a GitHub release (which will provide a version number and tarball). The rest is a pretty simple PR on the opam-coq-archive repo.

just created a release. That would be much appreciated!

**Comment by jeromesimeon** [comment]
> > I'd be happy to push an initial release to opam-coq-archive. All that's needed from the repo maintainer is a GitHub release (which will provide a version number and tarball). The rest is a pretty simple PR on the opam-coq-archive repo.
> 
> just created a release. That would be much appreciated!
> 

PR at https://github.com/coq/opam-coq-archive/pull/2621

> btw assuming you came here looking for an opam-based version of Wasmcert-Coq, [my fork](https://github.com/womeier/WasmCert-Coq) is almost there, may be useful until it is available through opam

Indeed I was! Thanks for the pointer.

**Comment by jeromesimeon** [comment]
release `0.1.0` is out:

```
zsh-5.8$ opam install coq-parseque
The following actions will be performed:
  ∗ install coq-parseque 0.1.0

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
[coq-parseque.0.1.0] downloaded from https://github.com/gallais/parseque/archive/refs/tags/v0.1.0.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><>  🐫 
∗ installed coq-parseque.0.1.0
Done.

```

**Comment by womeier** [comment]
thanks!
